<?xml version="1.0"?>
<robot name="eeduro_delta" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- <xacro:property name="pi" value="3.1415926535897931"/> -->
	<xacro:property name="dist_origin2arm_z" value="0.21"/>
	<xacro:property name="dist_origin2arm_xy_plane" value="${0.1/sqrt(3) -0.005}"/>

	<xacro:include filename="$(find eeduro_delta_description)/urdf/eeduro_delta_inertial.urdf.xacro"/>
	<!--<xacro:include filename="$(find eeduro_delta_description)/urdf/eeduro_delta.gazebo.xacro"/>-->

	<link name="world"/>

	<gazebo reference="world">
		<static>true</static>
	</gazebo>

	
	<joint name="fix_to_world" type="fixed">
	  <parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>

	
	<link name="base_link">
		<visual>
			<geometry>
				<mesh filename="package://eeduro_delta_description/meshes/delta_base.dae"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<mesh filename="package://eeduro_delta_description/meshes/delta_base_collision.dae"/>
			</geometry>
		</collision>
		<xacro:base_inertial/>
	</link>


	<xacro:delta_arm 
		parent="base_link" 
		arm_end_child="tool" 
		arm_nr="1" 
		joint4_type="urdf"
		angle1="${(-27)/180.0*pi}"
		angle2="${-0.8373228137897161 -(90-27)/180.0*pi}"
		angle3="${-pi/2 + 0.8373228137897161}"
		dist_xy="${dist_origin2arm_xy_plane}"
		x="0"		y="0"		z="${dist_origin2arm_z}"
		roll="0"		pitch="0"		yaw="${-pi/2}"
	/>

	<xacro:delta_arm
    parent="base_link"
    arm_end_child="tool"
    arm_nr="2"
    joint4_type="sdf"
    angle1="${(-27)/180.0*pi}"
    angle2="${-0.8373228137897161 -(90-27)/180.0*pi}"
    angle3="${-pi/2 + 0.8373228137897161}"
    dist_xy="${dist_origin2arm_xy_plane}"
    x="0"   y="0"   z="${dist_origin2arm_z}"
    roll="0"    pitch="0"   yaw="${pi/6}"
  />

	<xacro:delta_arm
    parent="base_link"
    arm_end_child="tool"
    arm_nr="3"
    joint4_type="sdf"
    angle1="${(-27)/180.0*pi}"
    angle2="${-0.8373228137897161 -(90-27)/180.0*pi}"
    angle3="${-pi/2 + 0.8373228137897161}"
    dist_xy="${dist_origin2arm_xy_plane}"
    x="0"   y="0"   z="${dist_origin2arm_z}"
    roll="0"    pitch="0"   yaw="${5*pi/6}"
  />



	<link name="tool">
	  <visual>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <mesh filename="package://eeduro_delta_description/meshes/tool_scaled.dae"/>
	    </geometry>
	  </visual>
	  <collision>
	    <origin xyz="0 0 0.023" rpy="${pi/2} 0 0"/>
	    <geometry>
	      <cylinder radius="0.007" length="0.051"/>
	    </geometry>
	  </collision>
		<xacro:tool_inertial/>
	</link>


	<gazebo reference="base_link">
	  <selfCollide>true</selfCollide>
	</gazebo>

	<gazebo reference="tool">
	  <selfCollide>true</selfCollide>
	</gazebo>

	<!-- x y z are the center of the robot, in the high:of the mounting-points for the arms -->
	<xacro:macro name="delta_arm" params="parent arm_end_child arm_nr joint4_type angle1 angle2 angle3 dist_xy x y z roll pitch yaw">
		<joint name="arm${arm_nr}_motor_joint" type="continuous">
		  <parent link="${parent}"/>
		  <child link="arm${arm_nr}_motor"/>
		  <origin xyz="${x +cos(yaw)*dist_xy -sin(yaw)*(0.04)} ${y +sin(yaw)*dist_xy +cos(yaw)*(0.04)} ${z -0.015}" rpy="${roll -pi/2} ${pitch} ${yaw -pi/2}"/>
		  <axis xyz="1 0 0"/>
		  <dynamics damping="0.0000001"/>
		</joint>
		<link name="arm${arm_nr}_motor">
	  <visual>
	    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
	    <geometry>
	      <cylinder radius="0.006" length="0.018"/>
	    </geometry>
	  </visual>
		<xacro:motor_inertial/>
		</link>

		<joint name="arm${arm_nr}_joint0" type="continuous">
		  <parent link="${parent}"/>
		  <child link="arm${arm_nr}_link1"/>
		  <!-- callculation X: 0  Y: -70.23..+17.5  Z: 210-15 -->
		  <origin xyz="${x +cos(yaw)*dist_xy} ${y +sin(yaw)*dist_xy}  ${z -0.015}" rpy="${roll -pi/2  +angle1} ${pitch} ${yaw -pi/2}"/>
		  <axis xyz="1 0 0"/>
		  <dynamics damping="0.0001"/>
		</joint>
		<link name="arm${arm_nr}_link1">
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <mesh filename="package://eeduro_delta_description/meshes/link1_scaled.dae"/>
		    </geometry>
		  </visual>
			<xacro:link1_inertial/>
		</link>

		<gazebo>
		  <joint name="arm${arm_nr}_gearbox" type="gearbox">
		    <parent>arm${arm_nr}_motor</parent>
		    <child>arm${arm_nr}_link1</child>
		    <gearbox_reference_body>${parent}</gearbox_reference_body>
		    <gearbox_ratio>-0.013176411</gearbox_ratio>
		    <axis>
					<use_parent_model_frame>false</use_parent_model_frame>
		      <xyz>1 0 0</xyz>
		    </axis>
		    <axis2>
					<use_parent_model_frame>false</use_parent_model_frame>
		      <xyz>1 0 0</xyz>
		    </axis2>
		  </joint>
		</gazebo>


		<joint name="arm${arm_nr}_joint1" type="continuous">
		  <parent link="arm${arm_nr}_link1"/>
		  <child link="arm${arm_nr}_link2"/>
		  <origin xyz="0 0 0.05" rpy="${angle2} 0 0"/>
		  <axis xyz="1 0 0"/>
		  <dynamics damping="0.00001"/>
		</joint>

		<link name="arm${arm_nr}_link2">
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <mesh filename="package://eeduro_delta_description/meshes/link2_scaled.dae"/>
		    </geometry>
		  </visual>
			<xacro:link2_inertial/>
		</link>

		
		<xacro:link3_with_joint arm_nr="${arm_nr}" suffix="_1" sign="+" joint3_type="urdf"/>
		<xacro:link3_with_joint arm_nr="${arm_nr}" suffix="_2" sign="-" joint3_type="sdf"/>

		<link name="arm${arm_nr}_link4">
		  <visual>
		    <origin xyz="0 -0.018 0" rpy="0 0 ${pi/2}"/>
		    <geometry>
		      <mesh filename="package://eeduro_delta_description/meshes/link2_scaled.dae"/>
		    </geometry>
		  </visual>
			<xacro:link4_inertial/>
		</link>

		<xacro:element xacro:name="joint4_${joint4_type}" arm_nr="${arm_nr}" child="${arm_end_child}" angle="${angle3}"/>
	</xacro:macro>

	<xacro:macro name="link3_with_joint" params="arm_nr suffix sign joint3_type">
		<joint name="arm${arm_nr}_joint2${suffix}" type="continuous">
		  <parent link="arm${arm_nr}_link2"/>
		  <child link="arm${arm_nr}_link3${suffix}"/>
		  <origin xyz="${sign}0.018 0 0" rpy="0 0 ${-pi/2}"/>
		  <axis xyz="1 0 0"/>
		  <dynamics damping="0.00001"/>
			<xacro:if value="${suffix == '_2'}">
				<mimic joint="arm${arm_nr}_joint2_1" multiplier="1" offset="0"/>
			</xacro:if>
		</joint>

		<link name="arm${arm_nr}_link3${suffix}">
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <mesh filename="package://eeduro_delta_description/meshes/link3_scaled.dae"/>
		    </geometry>
		  </visual>
			<xacro:link3_inertial/>
		</link>
		<xacro:element xacro:name="joint3_${joint3_type}" arm_nr="${arm_nr}" suffix="${suffix}"/>
	</xacro:macro>

	<xacro:macro name="joint3_urdf" params="arm_nr suffix">
			<joint name="arm${arm_nr}_joint3${suffix}" type="continuous">
			  <parent link="arm${arm_nr}_link3${suffix}"/>
			  <child link="arm${arm_nr}_link4"/>
			  <origin xyz="0 0 0.1" rpy="0 0 0"/>
			  <axis xyz="1 0 0"/>
			  <dynamics damping="0.00001"/>
				<mimic joint="arm${arm_nr}_joint2_1" multiplier="-1" offset="0"/>
			</joint>
	</xacro:macro>

	<xacro:macro name="joint3_sdf" params="arm_nr suffix">
		<gazebo>
			<joint name="arm${arm_nr}_joint3${suffix}" type="revolute">
			  <child>arm${arm_nr}_link4</child>
			  <parent>arm${arm_nr}_link3${suffix}</parent>
			  <pose>0 -0.036 0 0 0 0</pose>
			  <axis>
			    <use_parent_model_frame>false</use_parent_model_frame>
			    <xyz>1 0 0</xyz>
			    <limit>
			      <lower>-1e+16</lower>
			      <upper>1e+16</upper>
			    </limit>
			    <dynamics>
			      <damping>0.00001</damping>
			    </dynamics>
			  </axis>
			</joint>
		</gazebo>
  </xacro:macro>

	<xacro:macro name="joint4_urdf" params="arm_nr child angle">
		<joint name="arm${arm_nr}_joint4" type="continuous">
		  <parent link="arm${arm_nr}_link4"/>
		  <child link="${child}"/>
		  <origin xyz="0 -0.018 0" rpy="${angle} 0 ${pi/2}"/>
		  <axis xyz="1 0 0"/>
		  <dynamics damping="0.00001"/>
		</joint>
	</xacro:macro>

  <xacro:macro name="joint4_sdf" params="arm_nr child angle">
    <gazebo>
			<joint name="arm${arm_nr}_joint4" type="revolute">
	      <parent>${child}</parent>
	      <child>arm${arm_nr}_link4</child>
	      <pose>0 -0.018 0 ${angle} 0 ${pi/2}</pose>
				<axis>
          <use_parent_model_frame>false</use_parent_model_frame>
          <xyz>1 0 0</xyz>
          <limit>
            <lower>-1e+16</lower>
            <upper>1e+16</upper>
          </limit>
          <dynamics>
            <damping>0.00001</damping>
          </dynamics>
				</axis>
	    </joint>
		</gazebo>
  </xacro:macro>


</robot>
